### ISSUE TITLE
Change option colors, background opacity or font ?

### ISSUE THREAD

**Issue by JeT76-ESCP** [GBERESEARCH/optionvisualizer#1]
Great library !
I'd like to change the colors of the 3 curves, have a transparent background to save my file to an external pdf.

here is my MWE.

```
import os
import matplotlib.pyplot as plt
from optionvisualizer.visualizer import Visualizer


# Création de l'instance de la classe Visualizer
opt = Visualizer()

options = {
    'risk': True,
    'x_plot': 'price',
    'y_plot': 'delta',
    'G1': 100,
    'G2': 100,
    'G3': 100,
    'T1': 0.001,
    'T2': 0.25,
    'T3': 1,
}

# Generate the plot
opt.visualize(**options)

# Save the plot as a PDF with transparent background and 300 dpi
plt.savefig('my_plot.pdf', transparent=True, dpi=300)
```
1 - I don't see a reference to changing colors or fonts in your homepage.
2 - I don't see either a way to increase the range for x or y axis.
3 - my_plot.pdf is actually a white document. No plot.

thank you for your help !

**Comment by GBERESEARCH** [comment]
Thanks for your message. 

At the moment the line color and range parameters are hard coded in the respective functions but it should be fairly straightforward to add to the parameter dictionary so that they can be varied.  

The overall graph color scheme is set with the 'mpl-style' parameter currently to 'seaborn-v0_8-darkgrid' and there is a 'mpl_params' sub-dictionary that overrides some of these (font isn't explicitly set though this does set font size to 14). 

The code above only returns a white document because the output is currently plt.show() - it doesn't return a figure for you to perform the savefig operation on. I'll take a look at what that requires.

**Comment by JeT76-ESCP** [comment]
A big thank you for your answer !
What a great library I will obvioulsy publicize to my students in finance.
A bientôt.

**Comment by GBERESEARCH** [comment]
Thank you very much.

I've made those updates now (version is now 1.1.7 on PyPI).

This code should now give you the pdf export:

--------------
import os
import matplotlib.pyplot as plt
from optionvisualizer.visualizer import Visualizer


# Création de l'instance de la classe Visualizer
optv = Visualizer()

options = {
    'risk': True,
    'x_plot': 'price',
    'y_plot': 'gamma',
    'option3_color': 'yellow',
    'strike_min': 0.6,
    'strike_max': 1.4,
    #'time_min': 0.5,
    #'time_max': 2,
    #'linspace_granularity': 20,
    'graph_figure': True,
    'G1': 100,
    'G2': 100,
    'G3': 100,
    'T1': 0.001,
    'T2': 0.25,
    'T3': 1,
}

# Generate the plot
fig, ax = optv.visualize(**options)

fig.savefig('opt_vis.pdf', transparent=True, dpi=300)
--------------------

You can now set the line colors with option1_color etc. Min / Max strike, vol or time on x-axis (y-axis autoscales based on the min max of the 3 graphs). 'linspace_granularity' lets you choose how many options are priced between min and max x-axis points. The 'graph_figure' parameter set to True exports the figure and axis elements allowing you to use the savefig operation.

**Comment by JeT76-ESCP** [comment]
Thank you for your reactivity ! 
I feel now like a 3yo with a new toy...
Your other libraries are extremely pedagogical, expécially with your clear representations of skew.
With your automated download from yahoo finance, I have now 20 topics for Ms and phd students.

**Comment by GBERESEARCH** [comment]
Thank you. I'm glad you find them useful.
