### ISSUE TITLE
Greek of strategies?

### ISSUE THREAD

**Issue by tddschn** [GBERESEARCH/optionvisualizer#2]
Thanks you for making this amazing tool!

Can I visualize Greek of strategies? It seems that I can only visualize Greeks of straight calls and puts.

**Comment by GBERESEARCH** [comment]
Hi. Thanks for your message. Yes, only puts & calls. It's just meant to give an insight into how the greeks behave for those building block instruments. Doing the pricing in Python I felt would take too long to calculate surfaces for 2, 3 & 4 instrument combos
